using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static Haley.Internal.QueryFields;

namespace Haley.Internal {

    //Acknowledgement Status:
    //1 = Pending
    //2 = Delivered
    //3 = Processed(Idempotent)
    //4 = Failed
    
    internal class QRY_ACK_LOG {
        //For autogenerated Message ID
        public const string INSERT = $@"INSERT IGNORE INTO ack_log (transition_log, consumer, ack_status) VALUES ({TRANSITION_LOG}, {CONSUMER}, {ACK_STATUS}); SELECT * FROM ack_log WHERE consumer = {CONSUMER} AND transition_log = {TRANSITION_LOG} LIMIT 1;";
        //We pass the message ID ourselves, may be generated from the Application itself. But this can cause duplicates if not managed properly.
        public const string INSERT_WITH_MESSAGE = $@"INSERT IGNORE INTO ack_log (transition_log, consumer, ack_status, message_id) VALUES ({TRANSITION_LOG}, {CONSUMER}, {ACK_STATUS}, {MESSAGE_ID}); SELECT * FROM ack_log WHERE consumer = {CONSUMER} AND transition_log = {TRANSITION_LOG} LIMIT 1;";

        public const string MARK_BY_MESSAGE = $"UPDATE ack_log SET ack_status = {ACK_STATUS} WHERE message_id = {MESSAGE_ID};";
        public const string MARK = $"UPDATE ack_log SET ack_status = {ACK_STATUS} WHERE transition_log = {TRANSITION_LOG} AND consumer = {CONSUMER};";

        public const string GET_DUE_FOR_RETRY = $@"SELECT * FROM ack_log WHERE ack_status IN (1,2) AND retry_count < {MAX_RETRY} AND TIMESTAMPDIFF(MINUTE, COALESCE(last_retry, created), CURRENT_TIMESTAMP) >= {RETRY_AFTER_MIN} ORDER BY COALESCE(last_retry, created) ASC, id ASC LIMIT {SKIP}, {LIMIT};";
        public const string GET_FAILED = $@"SELECT * FROM ack_log WHERE ack_status = 4 ORDER BY COALESCE(last_retry, created) DESC, id DESC LIMIT {SKIP}, {LIMIT};";
        public const string BUMP_RETRY = $@"UPDATE ack_log SET retry_count = retry_count + 1, last_retry = CURRENT_TIMESTAMP WHERE id = {ID};";
        public const string GET_BY_TL_AND_CONSUMER = $"SELECT * FROM ack_log WHERE transition_log = {TRANSITION_LOG} AND consumer = {CONSUMER} LIMIT 1;";
        public const string GET_BY_MESSAGE = $"SELECT * FROM ack_log WHERE message_id = {MESSAGE_ID} LIMIT 1;";

        public const string EXISTS_BY_ID =$@"SELECT 1 FROM ack_log WHERE id = {ID} LIMIT 1;";
        public const string EXISTS_BY_MESSAGE_ID =$@"SELECT 1 FROM ack_log WHERE message_id = {MESSAGE_ID};"; //Message ID is unique, so it can only have one row.
        public const string EXISTS_BY_CONSUMER_AND_TRANSITION_LOG =$@"SELECT 1 FROM ack_log WHERE consumer = {CONSUMER} AND transition_log = {TRANSITION_LOG} LIMIT 1;";
    }
}
